version: '3'

services:
  server:
    container_name: mesto-express-server
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
