version: '3.9'

services:
  mongodb:
    container_name: impress-place-mongo-db
    image: mongo:7.0.5
    restart: always
    command: mongod --quiet --logpath /var/log/mongodb/mongo.log
    volumes:
      - mongodb:/data/db

  mongodb-test:
    container_name: impress-place-mongo-db-test
    image: mongo:7.0.5
    restart: always
    command: mongod --quiet --logpath /dev/null
    ports:
      - 27017:27017

  app:
    container_name: impress-place-api
    image: impress-place-api:dev
    depends_on:
      - mongodb
      - mongodb-test
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
    env_file:
      - .env

volumes:
  mongodb:
