version: '3.9'

services:
  mongodb:
    container_name: mesto-mongo-db
    image: mongo:7.0.5
    restart: always
    command: mongod --quiet --logpath /var/log/mongodb/mongo.log
    volumes:
      - mongodb:/data/db

  mongodb-test:
    container_name: mesto-mongo-db-test
    image: mongo:7.0.5
    restart: always
    ports:
      - 27017:27017

  app:
    container_name: mesto-express-server
    depends_on:
      - mongodb
      - mongodb-test
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
    environment:
      # map env vars from .env file
      - NODE_ENV=${NODE_ENV}
      - MONGODB_URI=${MONGODB_URI}
      - PORT=${PORT}
      - DB_NAME=${DB_NAME}
      - MONGODB_URI_TEST=${MONGODB_URI_TEST}
      - DB_NAME_TEST=${DB_NAME_TEST}

volumes:
  mongodb:
