FROM node:20-alpine as mesto-backend-base

WORKDIR /app

COPY package.json yarn.lock ./

# install exactly the same package version as in current project
RUN yarn --frozen-lockfile

COPY . .

EXPOSE 3000

CMD yarn dev
