FROM node:20-alpine as builder

WORKDIR /app

COPY . .

RUN yarn --frozen-lockfile
RUN yarn build

FROM node:20-alpine as runner

WORKDIR /app

COPY --from=builder ./app/build ./build
COPY package.json .
COPY yarn.lock .
RUN yarn --production

EXPOSE 3000

CMD yarn start
