FROM node:20-alpine as mesto-backend-base

WORKDIR /app

COPY . .

RUN yarn --frozen-lockfile
RUN yarn build

FROM node:20-alpine as mesto-backend-prod

WORKDIR /app

COPY --from=mesto-backend-base ./app/build ./build
COPY package.json .
COPY yarn.lock .
RUN yarn --production

EXPOSE 3000

CMD yarn start
