FROM node:20-alpine as mesto-backend-base

WORKDIR /app

COPY package.json .

RUN yarn

COPY . .

# Build localized versions of swagger API docs
RUN yarn swagger-i18n-extension translate-all ./docs/openapi.yaml

EXPOSE 3000

CMD yarn dev
